//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public int userid { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public long phNo { get; set; }
        public long whatsappPhNo { get; set; }
        public int userType { get; set; }
        public System.DateTime createdDate { get; set; }
        public System.DateTime modifiedDate { get; set; }
        public string skypeId { get; set; }
        public int isActive { get; set; }
        public string password { get; set; }
    }
}
